language: node_js
node_js:
- '8'
deploy:
  provider: npm
  email: simplex.rimor@gmail.com
  api_key:
    secure: Eq0hKtgOTHgwDBVhywHRiuFI9u8p6BpRzbq/ctI3MxU/fCJg5R3ZNPZjWgCMbDc62ksC9rm8T42geokuBs5rUaLL9IOr2MiL45u1VyJV82gAg9EdlumLZ4qPqc7hdvrmgJmAn1mjrr3Vt5XN2lWEaWGXZOM7Jq4j+XKBTy5NMVgD8lLOLwlBL5OrspnIgEK9XMVwt2GGDQ9eDvFrW1dgUX5OTmZO4OUINO15PZzXZqz+pMv3vVgR16VH8dFgH9lHJrxOUSnOsMTVdaoC1qz20vTKMV2C1/gfhjd+dYIvF9dJsjCxZkKNk73OIFVBT7OVBCCApYyBfiTYbPDtRkidHzGSAwIsI1NkPwiBJyv76Xz4xAAkVewd3gTEohMbrdqtnt+9eBqQ19aE2RtPGPaDFCIqwP/jxqN6uO4/Z+mzTLp0lAO5dL916QdxOFp9SCxXsVyBAtpxSIsIm0qpNK7n2wKDyhWcXNbLIsI04OUvMH0G2FVlUXzGLRxllMrRw/kbyXXT6E0S/y/4F0mpmsRwBhzyKtjHkyeZFnNc/STbIiUlXJlSotP4JsF+ZGsLbgrCUulqOShPp5P95hGUlFFhYMuvuADOrBqDaMzxxQ8sLi8xnkBfRM1LK19wmmQaVJdA8yCLtgzwEJ47BeILG8h6qDsZns7V6GEllUTb+qs4CKk=
  on:
    branch: master
    tags: true
    repo: genus-machina/eslint-plugin-node
